### ISSUE TITLE
Port hexrayx86 from IDA7.4 to IDA7.5

### ISSUE THREAD

**Issue by linhlhq** [EZForever/Things#1]
Can you show me how to patch hexrayx86 from IDA7.4 to IDA7.5? Thank you in advance for this help.

**Comment by EZForever** [comment]
Sorry for the late reply, but since I don't actually own a copy of IDA 7.4 (and hence the x86 decompiler), I'm afraid I can't help you.

However, I suspect that no major API change is done between IDA 7.4 and IDA 7.5, so the x86 decompiler might work out of the box. Just give it a try.

**Comment by mar1nahromina** [comment]
@EZForever can we discuss hexrays x86 in private? I got it from the bird. It should work with IDA 7.2 and 7.3, but some manipulations is still requided. Discord or telegram would be fine.

**Comment by EZForever** [comment]
@mar1nahromina ,

**Comment by EZForever** [comment]
@mar1nahromina :

First, there's really nothing to discuss about. Hexrays programmers design their software in a non-backwards- AND non-forward-compatible way, with critical API changes in nearly every minor update. My routine of "transplanting" hexrays, is, unsurprisingly, just put things together and hope that would work. If IDA crashes, then patch the execuables until IDA stops complaining. So in a word, in order to figure out how to do the patch, I need the hexrays executable or at least a full memory dump of IDA's crash site. I don't really get it when you say that you got your hexrays 7.4 "from the bird", but if you're *not* the legit owner of that copy, maybe you could send it to me and make my patching work easier.

Second, here are the links to the patched executables:  
[hexx64_7.2_7.3_20201113.public.dll](https://anonfiles.com/Nbcbrdpap4/hexx64_7.2_7.3_20201113.public_dll)  
[hexx64_7.5_7.x_20201113.public.dll](https://anonfiles.com/P5c5r7pcp8/hexx64_7.5_7.x_20201113.public_dll)  
However you should still try to patch the executables by yourself in the future, since I won't be updating these links.

You can contact me further via email, just give me your email address.

**Comment by mar1nahromina** [comment]
@EZForever hexrays 7.4 is fully compatible with IDA 7.2. Need to patch only IDA and key in runtime. I guess it's possible to port ctrl+f5 from hexrays x86 to x64 (demo version) and other features. You can DM at mar1nahromina@yandex.ru
